// Focused rolling-range regression; native fixture on port 3192.
// eslint-disable-next-line @typescript-eslint/no-unused-expressions -- Playwright CLI evaluates this function.
async page => {
  const check = (value, message) => { if (!value) throw Error(message); };
  const hour = 3_600_000, day = 24 * hour;
  let clockTime = Date.now();
  const range = () => ({ from: Math.ceil((clockTime - 60 * day) / hour) * hour, to: Math.floor(clockTime / hour) * hour });
  const stamp = () => new Date(clockTime).toISOString();
  const prices = () => ({ monitorId: 'oil', currency: 'USDT', intervalMs: hour, priceBasis: 'hour-open-mark', fetchedAt: stamp(), status: 'live', legs: [['bybit', 'BZUSDT', 100], ['bybit', 'CLUSDT', 80], ['binance', 'BZUSDT', 102], ['binance', 'CLUSDT', 81]].map(([exchange, symbol, price]) => ({ exchange, symbol, fetchedAt: stamp(), error: '', coverage: range(), rows: Array.from({ length: (range().to - range().from) / hour + 1 }, (_, i) => ({ time: range().from + i * hour, price })) })) });
  const funding = exchange => ({ exchange, monitorId: 'oil', currency: 'USDT', fetchedAt: stamp(), status: 'live', availability: 'supported', reason: '', left: { symbol: 'BZUSDT', fetchedAt: stamp(), error: '', coverage: range() }, right: { symbol: 'CLUSDT', fetchedAt: stamp(), error: '', coverage: range() }, rows: Array.from({ length: (range().to - range().from) / hour + 1 }, (_, i) => ({ time: range().from + i * hour, leftRate: 0.0001, rightRate: 0.0002 })) });
  await page.goto('about:blank');
  await page.unrouteAll({ behavior: 'wait' });
  await page.clock.install({ time: clockTime });
  await page.route('**/api/monitors/oil/exchanges/*/funding-history', route => route.fulfill({ json: funding(route.request().url().match(/exchanges\/([^/]+)\//)[1]) }));
  await page.route('**/api/monitors/oil/funding-hedge/prices', route => route.fulfill({ json: prices() }));
  await page.goto('http://127.0.0.1:3192/?monitor=oil');
  const panel = page.locator('[data-oil-hedge="true"]');
  const selected = panel.locator('[data-hedge-range-mode]');
  const refresh = panel.getByRole('button', { name: '刷新四腿模拟历史', exact: true });
  await panel.getByText('所选区间数据可计算', { exact: true }).waitFor();
  await panel.getByRole('button', { name: '最近 60 天', exact: true }).click();
  check(await selected.getAttribute('data-hedge-range-mode') === 'rolling', 'Preset is explicitly rolling');
  const oldFrom = Number(await selected.getAttribute('data-hedge-from'));
  await panel.locator('.oil-hedge-settings summary').click();
  await panel.getByLabel('四腿总开仓名义（USDT）', { exact: true }).fill('20000');
  const historyLength = await page.evaluate(() => history.length);
  clockTime += hour;
  await page.clock.fastForward(hour);
  await refresh.click();
  await page.locator(`[data-hedge-from="${oldFrom + hour}"]`).waitFor();
  await panel.getByText('所选区间数据可计算', { exact: true }).waitFor();
  check(await panel.getByLabel('四腿总开仓名义（USDT）', { exact: true }).inputValue() === '20000', 'Unapplied amount survives automatic rolling');
  check(await page.evaluate(() => history.length) === historyLength, 'Automatic rolling replaces URL without adding history entries');
  check(Number(new URL(page.url()).searchParams.get('hedgeFrom')) === oldFrom + hour, 'Link tracks the displayed rolling range');
  await panel.getByRole('button', { name: '应用模拟参数', exact: true }).click();
  check(await selected.getAttribute('data-hedge-range-mode') === 'rolling', 'Amount/fee-only apply preserves rolling');
  await panel.getByRole('button', { name: 'Bybit 空 BZ / 多 CL', exact: true }).click();
  check(await selected.getAttribute('data-hedge-range-mode') === 'rolling', 'Direction change preserves rolling');
  await panel.getByRole('button', { name: '最近 7 天', exact: true }).click();
  const fixedFrom = Number(await selected.getAttribute('data-hedge-from'));
  const shareUrl = page.url();
  await page.goto(shareUrl);
  await selected.waitFor();
  check(await selected.getAttribute('data-hedge-range-mode') === 'fixed', 'Explicit URL bounds restore a reproducible fixed range');
  clockTime += hour;
  await page.clock.fastForward(hour);
  await refresh.click();
  await panel.getByText('所选区间数据可计算', { exact: true }).waitFor();
  check(Number(await selected.getAttribute('data-hedge-from')) === fixedFrom, 'Restored URL range remains fixed after an hour');
  await panel.getByRole('button', { name: '最近 7 天', exact: true }).click();
  await panel.locator('.oil-hedge-settings summary').click();
  const start = panel.getByLabel('开仓（北京时间整点）', { exact: true });
  const edited = new Date(range().to - 3 * day + 8 * hour).toISOString().slice(0, 16);
  await start.fill(edited);
  clockTime += hour;
  await page.clock.fastForward(hour);
  await refresh.click();
  check(await start.inputValue() === edited, 'Unapplied custom dates survive automatic rolling');
  await panel.getByRole('button', { name: '应用模拟参数', exact: true }).click();
  check(await selected.getAttribute('data-hedge-range-mode') === 'fixed', 'Applying manually edited dates fixes the range');
  return { passed: true, checked: ['60-day hourly roll with trimmed source history', 'no extra history entries', 'amount/date draft retention', 'fee/direction preserve rolling', 'URL reproducibility', 'manual dates fixed'] };
}
